### ISSUE TITLE
Add support for RHEL 8 derivatives with FIPS=1

### ISSUE THREAD

**Issue by 2roll4life** [outsideopen/ansible-role-bigfix-client#12]
attempting to run this role against a machine with FIPS=1 will result in the following failure
`FAILED! => {"changed": false, "failures": [], "msg": "Unknown Error occurred: Transaction test error:\n  package BESAgent-10.0.4.32-rhe6.x86_64 does not verify: no digest\n", "rc": 1, "results": []}`

See https://access.redhat.com/solutions/4460971

a potential temporary workaround could be modifying the `RedHat.yml` install task to check the `ansible_fips` fact
more explicit checks could be made to verify the `os_family` and `distribution_major_version`
```
- name: Install BigFix Client
  yum:
    name: "/tmp/{{ bigfix_client_file_dest }}"
    state: present
  when: ansible_fips == false

- name: Install BigFix Client
  shell:
    cmd: rpm -ivh --nodigest --nofiledigest "/tmp/{{ bigfix_client_file_dest }}"
  when: ansible_fips == true
  ```
