### ISSUE TITLE
Idempotency issues

### ISSUE THREAD

**Issue by easpeagle** [outsideopen/ansible-role-bigfix-client#27]
Looks like this role isn't idempotent... specifically with this task in Install.yml:

```
- name: Record the installation
  file:
    dest: "{{ bigfix_client_conf_dir }}/.ansible_installed"
    state: touch
```
