### ISSUE TITLE
Role should do additional checks for besagent installed outside of ansible.

### ISSUE THREAD

**Issue by easpeagle** [outsideopen/ansible-role-bigfix-client#28]
The only check that this role is making to see if the besagent is already installed is the presence of the touched `.ansible_installed` file. Additional checks should probably be made against the OS package managers.

For Linux-based things... should be as easy as this (with additional logic if we want to do later version checking).

```
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Set fact for besagent version if installed
    ansible.builtin.set_fact:
      besagent_version: "{{ ansible_facts.packages['besagent'][0].version }}"
    when: "'besagent' in ansible_facts.packages"
```

The version could be used for additional, optional variables to not upgrade or downgrade...

For non-Linux... hooking those various package managers would add complexity...
